---
- name: Playbook para Github Actions
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Crear un archivo de ejemplo
      copy:
        dest: /tmp/ejemplo.txt
        content: "Este es un archivo de ejemplo creado por Ansible en Github Actions."
  
    - name: Mostrar mensaje por pantalla
      debug:
        msg: "El archivo de ejemplo ha sido creado correctamente."
      
    - name: Mostrar el contenido del archivo
      command: cat /tmp/ejemplo.txt
      register: output

    - name: Imprimir el contenido del archivo en la salida
      debug:
        msg: "{{ output.stdout }}"

    - name: Eliminar el archivo de ejemplo
      file:
        path: /tmp/ejemplo.txt
        state: absent