  name: Ansible CI/CD Example

  on:
    push:
      branches: [ "main" ]
    pull_request:
      branches: [ "main" ]

  jobs:
    lint:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.9'

        - name: Install Ansible and ansible-lint
          run: |
            python -m pip install --upgrade pip
            pip install ansible ansible-lint

        - name: Run ansible-lint
          run: ansible-lint playbooks/

    run_playbook:
      runs-on: ubuntu-latest
      needs: lint
      steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.9'

        - name: Install Ansible
          run: |
            python -m pip install --upgrade pip
            pip install ansible

        - name: Run Ansible Playbook
          run: ansible-playbook playbooks/site.yml -i localhost